tag : "python"  
  
* Using the next() method calls the __next__() method of the iterator. If the
  method returns _StopIteration_ exception, it signals (without raising an
  error) that the iterator has no more values to generate. If the caller is a
  _for_ loop, it notices the signal and exits.  

  [Reference](http://www.diveintopython3.net/iterators.html)  
